import { readFile, writeFile, mkdir, rm, cp, readdir } from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import MarkdownIt from 'markdown-it';
import sanitizeHtml from 'sanitize-html';
import sharp from 'sharp';

const md = new MarkdownIt({ html: false, linkify: true, typographer: true });
const root = process.cwd();
const out = path.join(root, 'dist');
const readYaml = async p => YAML.parse(await readFile(path.join(root,p),'utf8'));
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug = s => String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ə/g,'e').replace(/Ə/g,'e').replace(/ı/g,'i').replace(/İ/g,'i').replace(/ş/g,'s').replace(/Ş/g,'s').replace(/ç/g,'c').replace(/Ç/g,'c').replace(/ğ/g,'g').replace(/Ğ/g,'g').replace(/ö/g,'o').replace(/Ö/g,'o').replace(/ü/g,'u').replace(/Ü/g,'u').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const fmtDate = d => new Intl.DateTimeFormat('az-AZ',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${d}T12:00:00`));
const renderMd = body => sanitizeHtml(md.render(body), {allowedTags:sanitizeHtml.defaults.allowedTags.concat(['img','figure','figcaption']),allowedAttributes:{a:['href','title'],img:['src','alt','title','loading','width','height']},allowedSchemes:['http','https','mailto']});
async function collection(dir){
  const base=path.join(root,'content',dir); const files=(await readdir(base)).filter(f=>f.endsWith('.md'));
  return Promise.all(files.map(async file=>{const raw=await readFile(path.join(base,file),'utf8'); const m=raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/); if(!m)throw new Error(`Frontmatter yoxdur: ${file}`); return {...YAML.parse(m[1]),body:m[2],slug:file.replace(/\.md$/,''),source:`content/${dir}/${file}`};}));
}
const site=await readYaml('content/data/site.yml');
const nav=(await readYaml('content/data/navigation.yml')).filter(x=>x.active).sort((a,b)=>a.order-b.order);
const categories=(await readYaml('content/data/categories.yml')).filter(x=>x.active).sort((a,b)=>a.order-b.order);
const home=await readYaml('content/data/home.yml');
const articles=(await collection('articles')).filter(x=>x.status==='published').sort((a,b)=>new Date(b.date)-new Date(a.date));
const issues=(await collection('issues')).filter(x=>x.status==='published').sort((a,b)=>new Date(b.date)-new Date(a.date));
const pages=await collection('pages');

await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
await cp('public',out,{recursive:true}); await cp('src/styles.css',path.join(out,'styles.css'));
await cp('src/client.js',path.join(out,'client.js'));
await mkdir(path.join(out,'fonts'),{recursive:true});
for(const [src,dst] of [['cormorant-latin-wght-normal.woff2','cormorant-latin.woff2'],['cormorant-latin-ext-wght-normal.woff2','cormorant-latin-ext.woff2']]) await cp(path.join('node_modules/@fontsource-variable/cormorant/files',src),path.join(out,'fonts',dst));
for(const [src,dst] of [['manrope-latin-wght-normal.woff2','manrope-latin.woff2'],['manrope-latin-ext-wght-normal.woff2','manrope-latin-ext.woff2']]) await cp(path.join('node_modules/@fontsource-variable/manrope/files',src),path.join(out,'fonts',dst));

async function optimizeImages(){
  const names=['architecture','ceramics','fashion','portrait','interior','coast'];
  for(const name of names){const input=path.join('public/media',`${name}.jpg`);for(const width of [640,1200,2000]) await sharp(input).resize({width,withoutEnlargement:true}).webp({quality:82}).toFile(path.join(out,'media',`${name}-${width}.webp`));}
  await sharp('logoblack.PNG').trim({background:{r:0,g:0,b:0,alpha:0}}).resize({width:520}).png().toFile(path.join(out,'media','logo-dark.png'));
  await sharp('logowhite.PNG').trim({background:{r:0,g:0,b:0,alpha:0}}).resize({width:520}).png().toFile(path.join(out,'media','logo-light.png'));
  const cover=sharp({create:{width:1200,height:1600,channels:3,background:'#181818'}}); const svg=Buffer.from(`<svg width="1200" height="1600" xmlns="http://www.w3.org/2000/svg"><text x="600" y="360" fill="white" text-anchor="middle" font-family="Georgia" font-size="250">I’NAZ</text><text x="600" y="440" fill="#bda38d" text-anchor="middle" font-family="Georgia" font-size="44" letter-spacing="9">AYNAZ A.</text><line x1="120" y1="560" x2="1080" y2="560" stroke="#777"/><text x="120" y="715" fill="white" font-family="Georgia" font-size="96">İLK BAXIŞ</text><text x="120" y="800" fill="#bdbdbd" font-family="Arial" font-size="34">İNSANLAR · İDEYALAR · HEKAYƏLƏR</text><text x="120" y="1450" fill="white" font-family="Arial" font-size="30">№ 01 — SENTYABR 2026</text></svg>`); await cover.composite([{input:svg}]).jpeg({quality:90}).toFile(path.join(out,'media','issue-01.jpg'));
}
await optimizeImages();

const image = (src,alt='',eager=false,cls='') => {const name=path.basename(src,'.jpg');return `<picture><source type="image/webp" srcset="/media/${name}-640.webp 640w, /media/${name}-1200.webp 1200w, /media/${name}-2000.webp 2000w" sizes="(max-width:680px) 100vw, 80vw"><img class="${cls}" src="${src}" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} width="1600" height="1100"></picture>`};
const card = (a,detail=true) => `<a class="card" href="/hekayeler/${a.slug}/">${image(a.image,a.image_alt)}<h3>${esc(a.title)}</h3>${detail?`<p>${esc(a.description)}</p><time datetime="${a.date}">${fmtDate(a.date)}</time>`:''}</a>`;
const brand = () => `<a class="brand" href="/" aria-label="I’NAZ ana səhifə"><img src="${site.logo_dark}" alt="I’NAZ — AYNAZ A." width="520" height="180"></a>`;
const header = current => `<a class="skip" href="#main">Əsas məzmuna keç</a><div class="demo-notice">Sayt təqdimatı — mətn və buraxılışlar nümunə məzmundur</div><header class="wrap"><div class="masthead"><span class="masthead-note">Azərbaycanın redaksiya və lifestyle jurnalı</span><span class="mobile-tools"><a href="/axtaris/" aria-label="Axtarış"><i class="icon-search"></i></a></span>${brand()}<div class="masthead-right"><a href="/axtaris/"><i class="icon-search"></i> Axtarış</a><span>AZ</span></div><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menyu</button></div><nav class="navigation" id="main-nav" aria-label="Əsas naviqasiya">${nav.map(n=>`<a href="${n.url}" ${current===n.url?'aria-current="page"':''}>${esc(n.label)}</a>`).join('')}</nav></header>`;
const footer = () => `<footer class="site-footer"><div class="wrap"><div class="footer-main"><div class="footer-brand">${brand()}<p>${esc(site.footer)}</p></div><div><h2 class="footer-heading">Bölmələr</h2><nav class="footer-links">${nav.filter(x=>x.url!='/axtaris/').map(n=>`<a href="${n.url}">${esc(n.label)}</a>`).join('')}</nav></div><div><h2 class="footer-heading">Əlaqə</h2><div class="footer-links"><a href="mailto:${site.email}">${site.email}</a><a href="tel:+994552731121">${site.phone}</a><a href="${site.instagram}" target="_blank" rel="noopener noreferrer">Instagram</a><a href="${site.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} I’NAZ. Bütün hüquqlar qorunur.</span><nav><a href="/mexfilik/">Məxfilik</a><a href="/istifade-qaydalari/">İstifadə qaydaları</a><a href="/media/credits.json">Foto müəllifləri</a></nav></div></div></footer>`;
const doc = ({title,description,body,current='',extra='',canonical='/'}) => `<!doctype html><html lang="az"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.base_url}${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.base_url}${canonical}"><meta name="twitter:card" content="summary"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23191919'/%3E%3Ctext x='32' y='45' fill='white' font-family='Georgia' font-size='42' text-anchor='middle'%3EI%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/styles.css">${extra}</head><body>${header(current)}<main id="main">${body}</main>${footer()}<script src="/client.js" defer></script></body></html>`;
async function writeRoute(route,html){const d=path.join(out,route);await mkdir(d,{recursive:true});await writeFile(path.join(d,'index.html'),html)}

const hero=articles.find(a=>a.slug===home.hero)||articles[0]; const featured=articles.filter(a=>home.secondary.includes(a.slug)); const people=articles.filter(a=>a.category==='İnsanlar').slice(0,2); const ideas=articles.filter(a=>['İncəsənət və mədəniyyət','Brendlər və layihələr','Peşəkarlar'].includes(a.category)).filter(a=>a.slug!==hero.slug).slice(0,2); const issue=issues.find(i=>i.current)||issues[0];
const homeHtml=`<section class="hero wrap"><div class="section-top"><span class="eyebrow">Seçilmiş hekayə</span><a class="text-link" href="/hekayeler/">Bütün hekayələr <span>→</span></a></div><a href="/hekayeler/${hero.slug}/">${image(hero.image,hero.image_alt,true,'hero-image')}<div class="hero-caption"><h1>${esc(hero.title)}</h1><div><p>${esc(hero.description)}</p><span class="text-link">Oxumağa davam et <span>→</span></span></div></div></a></section><section class="section wrap"><div class="section-top"><h2>Son hekayələr</h2><span class="eyebrow">01 / Redaksiya</span></div><div class="grid">${featured.map(a=>card(a)).join('')}${card(articles.find(a=>a.slug==='isigin-ardinca'))}</div></section><section class="section people-section"><div class="wrap"><div class="section-top"><h2>İnsanlar</h2><a class="text-link" href="/insanlar/">Hamısına bax <span>→</span></a></div><div class="grid">${(people.length?people:[articles.find(a=>a.slug==='yaradiciligin-yeni-dili')]).map(a=>card(a)).join('')}</div></div></section><section class="section wrap"><div class="section-top"><h2>İdeyalar</h2><a class="text-link" href="/ideyalar/">Kəşf et <span>→</span></a></div><div class="grid grid-wide">${ideas.map(a=>card(a)).join('')}</div></section><section class="section rule"><div class="wrap issue-feature"><div class="issue-art"><img src="${issue.cover}" alt="${esc(issue.cover_alt)}" loading="lazy" width="900" height="1200"></div><div class="issue-copy"><span class="eyebrow">Cari buraxılış · ${issue.number}</span><h2>${esc(issue.title)}</h2><p>${esc(issue.description)}</p><a class="button" href="/jurnal/${issue.slug}/">Buraxılışa bax <span>→</span></a></div></div></section><section class="mission wrap"><span class="eyebrow">I’NAZ haqqında</span><h2>${esc(home.mission_title)}</h2><p>${esc(home.mission_text)}</p></section>`;
await writeRoute('',doc({title:`${site.name} Magazine`,description:site.description,body:homeHtml,canonical:'/'}));

function listing(title,desc,list,filter=true,current='/hekayeler/') {return `<header class="page-heading wrap"><h1>${title}</h1><p>${desc}</p></header><section class="catalog-controls"><div class="wrap">${filter?`<form class="search-line" action="/hekayeler/" method="get"><label class="field">Hekayələrdə axtar<input name="q" type="search" autocomplete="off" placeholder="Başlıq, müəllif və ya söz..."></label><label class="field sort-field">Sıralama<select name="sort"><option value="new">Ən yeni</option><option value="old">Ən köhnə</option></select></label></form><nav class="filters" aria-label="Kateqoriyalar"><a href="/hekayeler/" aria-current="true">Hamısı</a>${categories.map(c=>`<a href="/hekayeler/?category=${c.slug}" data-category="${c.slug}">${c.name}</a>`).join('')}</nav>`:''}</div></section><section class="listing wrap"><div class="results-meta"><span data-count>${list.length} hekayə</span><span class="muted">Nümunə məzmun</span></div><div class="grid" data-listing>${list.map(a=>`<div data-title="${esc(a.title.toLocaleLowerCase('az'))}" data-search="${esc(`${a.title} ${a.description} ${a.author} ${a.body}`.toLocaleLowerCase('az'))}" data-category="${slug(a.category)}" data-date="${a.date}">${card(a)}</div>`).join('')}</div><div class="empty" data-empty hidden><h2>Nəticə tapılmadı</h2><p>Axtarış sözünü və ya seçilmiş kateqoriyanı dəyişin.</p><a class="button secondary" href="/hekayeler/">Filtrləri təmizlə</a></div></section>`}
await writeRoute('hekayeler',doc({title:`Hekayələr — ${site.name}`,description:'I’NAZ jurnalının bütün hekayələri.',body:listing('Hekayələr','İnsanlar, ideyalar, yaradıcılıq və gündəlik həyat haqqında redaksiya materialları.',articles),current:'/hekayeler/',canonical:'/hekayeler/'}));
await writeRoute('insanlar',doc({title:`İnsanlar — ${site.name}`,description:'Öz yolunu yaradan insanların hekayələri.',body:listing('İnsanlar','Öz sahəsində fərqlənən və yeni yollar açan insanların portretləri.',articles.filter(a=>a.category==='İnsanlar'),false),current:'/insanlar/',canonical:'/insanlar/'}));
await writeRoute('ideyalar',doc({title:`İdeyalar — ${site.name}`,description:'Yaradıcı ideyalar və perspektivli layihələr.',body:listing('İdeyalar','Yaradıcılıq, sənət, peşə və gələcəyi formalaşdıran təşəbbüslər.',articles.filter(a=>a.category!=='İnsanlar'),false),current:'/ideyalar/',canonical:'/ideyalar/'}));

for(const a of articles){const bg=a.background||'#fff'; const lum=(()=>{const h=bg.replace('#','');const [r,g,b]=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255);return .2126*r+.7152*g+.0722*b})();const ink=a.text_color==='white'?'#fff':a.text_color==='black'?'#191919':lum>.55?'#191919':'#fff';const json=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:a.title,datePublished:a.date,author:{'@type':'Organization',name:a.author},publisher:{'@type':'Organization',name:'I’NAZ'},image:`${site.base_url}${a.image}`,description:a.description}).replace(/</g,'\\u003c');const body=`<article class="article-shell" style="--article-bg:${bg};--article-ink:${ink}"><header class="article-header"><span class="eyebrow">${esc(a.category)}</span><h1>${esc(a.title)}</h1><p class="article-deck">${esc(a.description)}</p><div class="byline"><span>${esc(a.author)}</span><time datetime="${a.date}">${fmtDate(a.date)}</time></div>${a.partner?'<span class="sample-label">Tərəfdaş materialı</span>':''}${a.sample?'<span class="sample-label">Nümunə məzmun</span>':''}</header><figure class="article-cover wrap">${image(a.image,a.image_alt,true)}<figcaption class="muted">Foto: ${esc(a.photo_credit)}</figcaption></figure><div class="article-body prose">${renderMd(a.body)}<div class="share"><strong>Paylaş</strong><a href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(site.base_url+`/hekayeler/${a.slug}/`)}" target="_blank" rel="noopener noreferrer">Facebook</a><a href="https://twitter.com/intent/tweet?url=${encodeURIComponent(site.base_url+`/hekayeler/${a.slug}/`)}&text=${encodeURIComponent(a.title)}" target="_blank" rel="noopener noreferrer">X</a><button type="button" data-copy-link>Keçidi köçür</button></div></div></article><section class="related section wrap"><div class="section-top"><h2>Oxşar hekayələr</h2></div><div class="grid">${articles.filter(x=>x.slug!==a.slug).slice(0,3).map(x=>card(x,false)).join('')}</div></section>`;await writeRoute(`hekayeler/${a.slug}`,doc({title:a.seo_title||`${a.title} — ${site.name}`,description:a.seo_description||a.description,body,current:'/hekayeler/',canonical:`/hekayeler/${a.slug}/`,extra:`<script type="application/ld+json">${json}</script>`}));}

const archive=`<header class="page-heading wrap"><h1>Jurnal</h1><p>I’NAZ-ın cari buraxılışı və arxivi.</p></header><section class="section rule"><div class="wrap issue-feature"><div class="issue-art"><img src="${issue.cover}" alt="${esc(issue.cover_alt)}" width="900" height="1200"></div><div class="issue-copy"><span class="eyebrow">Cari buraxılış · ${issue.number}</span><h2>${esc(issue.title)}</h2><p>${esc(issue.description)}</p><a class="button" href="/jurnal/${issue.slug}/">Buraxılışa bax</a></div></div></section><section class="section wrap"><div class="section-top"><h2>Arxiv</h2></div><div class="grid archive">${issues.map(i=>`<a class="card" href="/jurnal/${i.slug}/"><img src="${i.cover}" alt="${esc(i.cover_alt)}" loading="lazy" width="900" height="1200"><h3>${esc(i.title)}</h3><p>${i.number} · ${i.month} ${i.year}</p></a>`).join('')}</div></section>`; await writeRoute('jurnal',doc({title:`Jurnal — ${site.name}`,description:'I’NAZ jurnal buraxılışları.',body:archive,current:'/jurnal/',canonical:'/jurnal/'}));
for(const i of issues){const body=`<article class="issue-page wrap section"><div class="issue-feature"><div class="issue-art"><img src="${i.cover}" alt="${esc(i.cover_alt)}" width="900" height="1200"></div><div class="issue-copy"><span class="eyebrow">${i.number} · ${i.month} ${i.year}</span><h1>${esc(i.title)}</h1><p>${esc(i.description)}</p>${i.sample?'<span class="sample-label">Nümunə buraxılış</span>':''}${i.external_url?`<a class="button" href="${i.external_url}" target="_blank" rel="noopener noreferrer">Oxumağa başla</a>`:i.pdf?`<a class="button" href="${i.pdf}">PDF-i aç</a>`:'<p class="muted" style="margin-top:25px">Oxuma keçidi hələ əlavə edilməyib.</p>'}</div></div><div class="prose issue-toc">${renderMd(i.body)}</div></article>`;await writeRoute(`jurnal/${i.slug}`,doc({title:`${i.title} — ${site.name}`,description:i.description,body,current:'/jurnal/',canonical:`/jurnal/${i.slug}/`}));}

const about=pages.find(p=>p.slug==='about');const aboutBody=`<section class="section wrap static-layout"><header><span class="eyebrow">I’NAZ Magazine</span><h1>${about.title}</h1></header><div class="prose">${renderMd(about.body)}<div class="contact-block"><h2>Əlaqə və əməkdaşlıq</h2><p>Redaksiya, reklam və əməkdaşlıq müraciətləri üçün:</p><p><a href="mailto:${site.email}">${site.email}</a><br><a href="tel:+994552731121">${site.phone}</a><br><a href="${site.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp ilə yazın</a><br><a href="${site.instagram}" target="_blank" rel="noopener noreferrer">Instagram</a></p></div></div></section>`;await writeRoute('haqqimizda',doc({title:`Haqqımızda — ${site.name}`,description:about.description,body:aboutBody,current:'/haqqimizda/',canonical:'/haqqimizda/'}));
for(const [s,r] of [['mexfilik','privacy'],['istifade-qaydalari','terms']]){const p=pages.find(x=>x.slug===r);await writeRoute(s,doc({title:`${p.title} — ${site.name}`,description:p.description,body:`<section class="section wrap static-layout"><header><h1>${p.title}</h1></header><div class="prose">${renderMd(p.body)}</div></section>`,canonical:`/${s}/`}));}
const searchBody=`<header class="page-heading wrap"><h1>Axtarış</h1><p>I’NAZ məqalələrində başlıq, müəllif və mətn üzrə axtarın.</p></header><section class="listing wrap"><label class="field"><span class="eyebrow">Axtarış sözü</span><input type="search" data-global-search autocomplete="off" autofocus placeholder="Məsələn: yaradıcılıq"></label><p class="status" data-search-status aria-live="polite">Axtarmaq üçün ən azı iki hərf yazın.</p><div class="grid" data-search-results></div></section>`;await writeRoute('axtaris',doc({title:`Axtarış — ${site.name}`,description:'I’NAZ saytında axtarış.',body:searchBody,current:'/axtaris/',canonical:'/axtaris/'}));
await writeFile(path.join(out,'search-index.json'),JSON.stringify(articles.map(a=>({title:a.title,description:a.description,author:a.author,date:a.date,url:`/hekayeler/${a.slug}/`,image:a.image,alt:a.image_alt,text:a.body.replace(/[#>*_`]/g,' ')}))));
await writeFile(path.join(out,'404.html'),doc({title:`Səhifə tapılmadı — ${site.name}`,description:'Axtardığınız səhifə tapılmadı.',body:`<section class="error-page"><h1>404</h1><h2>Səhifə tapılmadı</h2><p>Axtardığınız ünvan dəyişmiş və ya silinmiş ola bilər.</p><a class="button" href="/">Ana səhifəyə qayıt</a></section>`}));
const urls=['/','/hekayeler/','/insanlar/','/ideyalar/','/jurnal/','/haqqimizda/','/axtaris/','/mexfilik/','/istifade-qaydalari/',...articles.map(a=>`/hekayeler/${a.slug}/`),...issues.map(i=>`/jurnal/${i.slug}/`)];
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${site.base_url}${u}</loc></url>`).join('')}</urlset>`);await writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${site.base_url}/sitemap.xml\n`);await writeFile(path.join(out,'_headers'),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n`);
console.log(`I’NAZ build tamamlandı: ${articles.length} məqalə, ${urls.length} URL`);
